version: 2

sources:
    - name: COVID19_Epidemiological_Data
      description: 'Ceci est un test.'
      database: COVID19_Epidemiological_Data
      schema: PUBLIC
      tables:
        - name: DEMOGRAPHICS
          description: 'Ceci est un test.'

models:
  - name: w_country_code
    description: A starter dbt model for covid data with country
    columns:
      - name: name
        description: The primary key for this table
        data_tests:
          - not_null
      - name: state
        description: The primary key for this table
        data_tests:
          - loop_test:
              column_name: state
              val: CA